### ISSUE TITLE
product stock: add has_stock; exact quantity not always realistic

### ISSUE THREAD

**Issue by danmilon** [open-csa/open-csa-ng#1]
Currently in the `ProductStock`  model we keep the `quantity` (required) of in-stock items. Keeping this property in sync with reality is realistic for products that either we store ourselves, or the producer can guarantee a given amount, but for fresh vegetables it's not an option.

The proposed fix is to have both `quantity`  and `has_stock`  to cover both cases. e.g. we can set has_stock to `True` for both cases, and if quantity is not an option set it to zero or `null`.
if it's out of stock, set `has_stock` to `false`.

**Comment by kkerk** [comment]
After discussion with @danmilon we came up with a more explicit solution. We propose to keep the `quantity` variable for the "stockable" items, the ones that are pre-stocked, and add two more boolean variables, 
- `is_available`
  - indicates whether the product is available in general or not
- `is_stockable` 
  - indicates whether the specific product is distributed based on the stock we already have or not

The `is_available` variable will be `True` for all available products, for products like fresh vegetables and for products that can be stocked alike. On the other hand, it can be `False` for various reasons, e.g. it's out of season, the producer is out this product and does not plan to provide them anymore for the current season, or it is discontinued in general. However, if this is `False`, we will not show the product at all in the ordering form.  

The `is_available` variable will be `True` for "stockable" items, like jars of olives for example, which either we pre-stock or the producer guarantees to have in stock and `False` for products which we cannot realistically keep track of their stock but are brought from the producer on demand and based on their availability at that time. If `is_stockable` is `True` for a product, then we will advise its `quantity` when orders are placed and update it. If it is `0`, then we will not permit a user to add it to his cart and we can show a message like _"Currently not in stock"_. 

Now, regarding the `quantity` variable, any update to the `quantity` value will be done **after the user has placed an order**, not while the items are in the cart. This may result in a problematic case where an item which is in the cart of consumer goes out of stock before the consumer checkouts/confirms his order. In that case, the final placement of the order should not be possible, a warning message should  inform him that the product is no longer in stock and he should be sent back to his updated cart. The final update of the `quantity` value should be done after the verification from an admin that the orders were delivered, if a "stockable" item was not delivered, then the `ordered_quantity`(not the actual name of the var) should be added back to the `quantity`.
