### ISSUE TITLE
send transactional emails

### ISSUE THREAD

**Issue by danmilon** [open-csa/open-csa-ng#2]
Once we figure out how to do one, this should be broken down into other issues for each case where we want to send transactional emails. (e.g. at the end of the orders period send email to producers to remind to check their orders).

**Comment by ggalan87** [comment]
Considering the relation of some of the producers with their e-mail, I think that there should also be an SMS notification system :)

**Comment by danmilon** [comment]
Indeed, I was thinking about this too. Could you create a `2.0` milestone, and create the issue for sms notifications, label it as `feature-major` and add it to the `2.0` milestone, so that we keep track of it?
